package {
  
import flash.display.*;
import flash.events.*;
import flash.utils.*;
import flash.text.*;
import flash.system.*;
import flash.net.*;
import flash.ui.*;
import flash.external.*;
public class LzApplication extends LFCApplication {
override public function runToplevelDefinitions () {;
;

[Embed(source="/data/users/raju/data/Development/openlaszlo/workspace/openlaszlo-flashbuilder-project/temp/lzx/resources/img/free.jpg")]
var __embed_lzasset_freeImg:Class;
;LzResourceLibrary.freeImg = {ptype: "ar", assetclass: __embed_lzasset_freeImg, frames: ["resources/img/free.jpg"], width: 300, height: 300};/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#9 -*- */
lz.ClassAttributeTypes["Instance"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Object"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#33 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#41 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_BooleanPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#44 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_CDATAPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#48 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_CSSDeclarationPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#58 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_ColorPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#62 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_ExpressionPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#65 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_NumberPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#68 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_SizePresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#71 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_StringPresentationType"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$$lz$class_PresentationType"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#74 -*- */
lz.ClassAttributeTypes["$lfc$$lz$class_TypeService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#82 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_PresentationTypeValue"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#101 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_userClassPlacement"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#104 -*- */
lz.ClassAttributeTypes["$lfc$$lzsc$runtime"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#108 -*- */
lz.ClassAttributeTypes["$lfc$DojoExternalInterfaceClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#139 -*- */
lz.ClassAttributeTypes["$lfc$ExpressInstall"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#159 -*- */
lz.ClassAttributeTypes["$lfc$JSRegExp"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#164 -*- */
lz.ClassAttributeTypes["$lfc$LFCApplication"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#175 -*- */
lz.ClassAttributeTypes["$lfc$LZOApplication"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#179 -*- */
lz.ClassAttributeTypes["$lfc$LzAS2DebugService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#185 -*- */
lz.ClassAttributeTypes["$lfc$LzAsset"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#193 -*- */
lz.ClassAttributeTypes["$lfc$LzAudioKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#203 -*- */
lz.ClassAttributeTypes["$lfc$LzAudioService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#214 -*- */
lz.ClassAttributeTypes["$lfc$LzBacktrace"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#225 -*- */
lz.ClassAttributeTypes["$lfc$LzBootstrapDebugConsole"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#232 -*- */
lz.ClassAttributeTypes["$lfc$LzDHTMLDebugConsole"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzBootstrapDebugConsole"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#240 -*- */
lz.ClassAttributeTypes["$lfc$LzFlashRemoteDebugConsole"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzBootstrapDebugConsole"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#257 -*- */
lz.ClassAttributeTypes["$lfc$LzBootstrapDebugLogger"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#262 -*- */
lz.ClassAttributeTypes["$lfc$LzBootstrapDebugService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#279 -*- */
lz.ClassAttributeTypes["$lfc$LzBootstrapMessage"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#303 -*- */
lz.ClassAttributeTypes["$lfc$LzDebugMessage"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzBootstrapMessage"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#319 -*- */
lz.ClassAttributeTypes["$lfc$LzMessage"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDebugMessage"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#322 -*- */
lz.ClassAttributeTypes["$lfc$LzBrowserKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#343 -*- */
lz.ClassAttributeTypes["$lfc$LzBrowserService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#374 -*- */
lz.ClassAttributeTypes["$lfc$LzCSSStyleClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#386 -*- */
lz.ClassAttributeTypes["$lfc$LzCSSStyleDeclaration"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#391 -*- */
lz.ClassAttributeTypes["$lfc$LzCSSStyleRule"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#402 -*- */
lz.ClassAttributeTypes["$lfc$LzCache"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#409 -*- */
lz.ClassAttributeTypes["$lfc$LzColorUtils"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#440 -*- */
lz.ClassAttributeTypes["$lfc$LzContextMenuItemKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#453 -*- */
lz.ClassAttributeTypes["$lfc$LzContextMenuKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#466 -*- */
lz.ClassAttributeTypes["$lfc$LzDataElementMixin"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {attributes: "string", nodeName: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#503 -*- */
lz.ClassAttributeTypes["$lfc$LzDataNodeMixin"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#541 -*- */
lz.ClassAttributeTypes["$lfc$LzDebug"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#544 -*- */
lz.ClassAttributeTypes["$lfc$LzDebugConsole"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#559 -*- */
lz.ClassAttributeTypes["$lfc$LzDebuggerWindowConsoleBridge"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDebugConsole"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#573 -*- */
lz.ClassAttributeTypes["$lfc$LzDebugService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#588 -*- */
lz.ClassAttributeTypes["$lfc$LzAS3DebugService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDebugService"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#603 -*- */
lz.ClassAttributeTypes["$lfc$LzDHTMLDebugService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDebugService"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#616 -*- */
lz.ClassAttributeTypes["$lfc$LzDeclaredEventClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#624 -*- */
lz.ClassAttributeTypes["event"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDeclaredEventClass"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#633 -*- */
lz.ClassAttributeTypes["$lfc$LzNotifyingEvent"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["event"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#640 -*- */
lz.ClassAttributeTypes["$lfc$LzIdleEvent"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzNotifyingEvent"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#644 -*- */
lz.ClassAttributeTypes["$lfc$LzTextlinkEvent"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzNotifyingEvent"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#648 -*- */
lz.ClassAttributeTypes["$lfc$LzTextscrollEvent"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzNotifyingEvent"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#664 -*- */
lz.ClassAttributeTypes["$lfc$LzEditManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#665 -*- */
lz.ClassAttributeTypes["$lfc$LzError"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#668 -*- */
lz.ClassAttributeTypes["$lfc$LzEventable"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#680 -*- */
lz.ClassAttributeTypes["$lfc$AnonDatasetGenerator"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#685 -*- */
lz.ClassAttributeTypes["$lfc$LzCursorService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#694 -*- */
lz.ClassAttributeTypes["$lfc$LzDataNode"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#698 -*- */
lz.ClassAttributeTypes["$lfc$LzDataElement"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDataNode"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#711 -*- */
lz.ClassAttributeTypes["$lfc$LzDataText"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDataNode"], {data: "string", nodeName: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#724 -*- */
lz.ClassAttributeTypes["$lfc$LzDataProvider"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#729 -*- */
lz.ClassAttributeTypes["$lfc$LzHTTPDataProvider"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDataProvider"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#741 -*- */
lz.ClassAttributeTypes["$lfc$LzDataRequest"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {ERROR: "string", LOADING: "string", READY: "string", SUCCESS: "string", TIMEOUT: "string", error: "string", rawdata: "string", requestor: "string", src: "string", status: "string", timeout: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#762 -*- */
lz.ClassAttributeTypes["$lfc$LzHTTPDataRequest"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzDataRequest"], {cacheable: "boolean", clientcacheable: "boolean", credentialled: "boolean", getresponseheaders: "boolean", loadstarttime: "number", loadtime: "number", method: "string", multirequest: "boolean", nsprefix: "boolean", parsexml: "boolean", postbody: "string", proxied: "boolean", proxyurl: "string", queryparams: "string", queuerequests: "boolean", requestheaders: "string", responseheaders: "string", secure: "boolean", secureport: "number", serverproxyargs: "string", trimwhitespace: "boolean", xmldata: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#809 -*- */
lz.ClassAttributeTypes["$lfc$LzFocusService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {focuswithkey: "boolean", lastfocus: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#842 -*- */
lz.ClassAttributeTypes["$lfc$LzGlobalMouseService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#874 -*- */
lz.ClassAttributeTypes["$lfc$LzHistoryService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {_persistso: "string", offset: "number", persist: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#902 -*- */
lz.ClassAttributeTypes["$lfc$LzIdleService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#911 -*- */
lz.ClassAttributeTypes["$lfc$LzInstantiatorService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {trickletime: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#932 -*- */
lz.ClassAttributeTypes["$lfc$LzKeysService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {mousewheeldelta: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#957 -*- */
lz.ClassAttributeTypes["$lfc$LzLoader"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#992 -*- */
lz.ClassAttributeTypes["$lfc$LzModeManagerService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2316 -*- */
lz.ClassAttributeTypes["$lfc$LzStyleAttrBinder"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2326 -*- */
lz.ClassAttributeTypes["$lfc$LzTrackService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1010 -*- */
lz.ClassAttributeTypes["node"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {classroot: "string", cloneManager: "string", datapath: "string", defaultplacement: "string", id: "ID", ignoreplacement: "boolean", immediateparent: "string", inited: "boolean", initstage: "string", isinited: "boolean", name: "token", nodeLevel: "number", options: "css", parent: "string", placement: "string", styleclass: "string", subnodes: "string", transition: "string", "with": "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1556 -*- */
lz.ClassAttributeTypes["$lfc$LzLibraryCleanup"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1562 -*- */
lz.ClassAttributeTypes["$lfc$LzRefNode"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1128 -*- */
lz.ClassAttributeTypes["animatorgroup"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {attribute: "token", duration: "number", from: "number", indirect: "boolean", isactive: "boolean", motion: "string", paused: "boolean", process: "string", relative: "boolean", repeat: "number", start: "boolean", started: "boolean", target: "reference", to: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1186 -*- */
lz.ClassAttributeTypes["animator"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["animatorgroup"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1205 -*- */
lz.ClassAttributeTypes["contextmenu"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1223 -*- */
lz.ClassAttributeTypes["contextmenuitem"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {caption: "string", enabled: "boolean", separatorbefore: "boolean", visible: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1245 -*- */
lz.ClassAttributeTypes["datapointer"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {context: "string", p: "string", rerunxpath: "boolean", xpath: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1324 -*- */
lz.ClassAttributeTypes["$lfc$LzDataAttrBind"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["datapointer"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1336 -*- */
lz.ClassAttributeTypes["datapath"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["datapointer"], {axis: "string", pooling: "boolean", replication: "string", sortorder: "string", sortpath: "string", spacing: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1374 -*- */
lz.ClassAttributeTypes["$lfc$LzReplicationManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["datapath"], {visible: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1420 -*- */
lz.ClassAttributeTypes["$lfc$LzLazyReplicationManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzReplicationManager"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1432 -*- */
lz.ClassAttributeTypes["$lfc$LzResizeReplicationManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzLazyReplicationManager"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1442 -*- */
lz.ClassAttributeTypes["dataset"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {acceptencodings: "boolean", autorequest: "boolean", cacheable: "boolean", clientcacheable: "boolean", credentialled: "boolean", datafromchild: "boolean", getresponseheaders: "boolean", multirequest: "boolean", nsprefix: "boolean", params: "string", postbody: "string", proxied: "inheritableBoolean", proxyurl: "string", querystring: "string", querytype: "string", queuerequests: "boolean", rawdata: "string", request: "boolean", secureport: "number", src: "string", timeout: "number", trimwhitespace: "boolean", type: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3273 -*- */
lz.ClassAttributeTypes["frame"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {src: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1534 -*- */
lz.ClassAttributeTypes["import"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {href: "string", proxied: "inheritableBoolean", stage: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1566 -*- */
lz.ClassAttributeTypes["script"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {src: "string", type: "string", when: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1573 -*- */
lz.ClassAttributeTypes["state"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {applied: "boolean", pooling: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1597 -*- */
lz.ClassAttributeTypes["view"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["node"], {aaactive: "boolean", aadescription: "string", aaname: "string", aasilent: "boolean", aatabindex: "number", align: "string", backgroundrepeat: "string", bgcolor: "color", cachebitmap: "boolean", capabilities: "string", clickable: "boolean", clickregion: "string", clip: "boolean", contextmenu: "string", cornerradius: "string", cursor: "token", fgcolor: "color", focusable: "boolean", focustrap: "boolean", font: "string", fontsize: "size", fontstyle: "string", frame: "numberExpression", framesloadratio: "number", hasdirectionallayout: "boolean", hassetheight: "boolean", hassetwidth: "boolean", height: "size", layout: "css", loadratio: "number", mask: "string", opacity: "number", pixellock: "boolean", playing: "boolean", resource: "string", resourceheight: "number", resourcewidth: "number", rotation: "numberExpression", shadowangle: "number", shadowblurradius: "number", shadowcolor: "color", shadowdistance: "number", showhandcursor: "boolean", source: "string", stretches: "string", subviews: "string", tintcolor: "string", totalframes: "number", unstretchedheight: "number", unstretchedwidth: "number", usegetbounds: "boolean", valign: "string", visibility: "string", visible: "boolean", width: "size", x: "numberExpression", xoffset: "numberExpression", xscale: "numberExpression", y: "numberExpression", yoffset: "numberExpression", yscale: "numberExpression"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1940 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_8l2c5f"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1952 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_lzcontextmenu"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1973 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_lzcontextmenuseparator"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1979 -*- */
lz.ClassAttributeTypes["canvas"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {accessible: "boolean", allowfullscreen: "boolean", appbuilddate: "string", compileroptions: "string", dataloadtimeout: "numberExpression", datasets: "string", debug: "boolean", defaultdataprovider: "string", embedfonts: "boolean", framerate: "number", fullscreen: "boolean", history: "boolean", httpdataprovider: "string", id: "ID", lpsbuild: "string", lpsbuilddate: "string", lpsrelease: "string", lpsversion: "string", mediaerrortimeout: "numberExpression", medialoadtimeout: "numberExpression", percentcreated: "number", proxied: "inheritableBoolean", runtime: "string", screenorientation: "boolean", scriptlimits: "css", title: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3251 -*- */
lz.ClassAttributeTypes["library"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["canvas"], {href: "string", includes: "string", proxied: "inheritableBoolean", validate: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2104 -*- */
lz.ClassAttributeTypes["text"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {antiAliasType: "string", cdata: "cdata", direction: "string", embedfonts: "boolean", gridFit: "string", hscroll: "number", letterspacing: "number", lineheight: "number", maxhscroll: "number", maxlength: "numberExpression", maxscroll: "number", multiline: "boolean", pattern: "string", resize: "boolean", scroll: "number", scrollevents: "boolean", scrollheight: "number", scrollwidth: "number", selectable: "boolean", sharpness: "number", text: "html", textalign: "string", textdecoration: "string", textindent: "number", thickness: "number", xscroll: "number", yscroll: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2263 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_lzcontextmenudisabled"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["text"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2266 -*- */
lz.ClassAttributeTypes["$lfc$$lzc$class_lzcontextmenutext"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["text"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2273 -*- */
lz.ClassAttributeTypes["inputtext"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["text"], {enabled: "boolean", password: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2298 -*- */
lz.ClassAttributeTypes["params"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzEventable"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2347 -*- */
lz.ClassAttributeTypes["$lfc$LzFontManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2355 -*- */
lz.ClassAttributeTypes["$lfc$LzFormatCallback"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2363 -*- */
lz.ClassAttributeTypes["$lfc$LzHTTPLoader"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2439 -*- */
lz.ClassAttributeTypes["$lfc$LzIdleKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2440 -*- */
lz.ClassAttributeTypes["$lfc$LzInfo"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2443 -*- */
lz.ClassAttributeTypes["$lfc$LzInheritedHash"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2446 -*- */
lz.ClassAttributeTypes["$lfc$LzInputTextSprite"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2477 -*- */
lz.ClassAttributeTypes["$lfc$LzKernelTimer"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2478 -*- */
lz.ClassAttributeTypes["$lfc$LzKernelUtils"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2485 -*- */
lz.ClassAttributeTypes["$lfc$LzKeyboardKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2493 -*- */
lz.ClassAttributeTypes["$lfc$LzLibraryLoader"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2502 -*- */
lz.ClassAttributeTypes["$lfc$LzMediaLoader"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2516 -*- */
lz.ClassAttributeTypes["$lfc$LzMessageAnnotation"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2528 -*- */
lz.ClassAttributeTypes["$lfc$LzMonitor"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2531 -*- */
lz.ClassAttributeTypes["$lfc$LzMouseKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2555 -*- */
lz.ClassAttributeTypes["$lfc$LzParsedPath"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2562 -*- */
lz.ClassAttributeTypes["$lfc$LzScreenKernel"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2569 -*- */
lz.ClassAttributeTypes["$lfc$LzSourceMessage"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2593 -*- */
lz.ClassAttributeTypes["$lfc$LzSprite"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2885 -*- */
lz.ClassAttributeTypes["$lfc$LzStyleSheet"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2888 -*- */
lz.ClassAttributeTypes["$lfc$LzCSSStyleSheet"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzStyleSheet"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2892 -*- */
lz.ClassAttributeTypes["$lfc$LzTLFTextField"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2893 -*- */
lz.ClassAttributeTypes["$lfc$LzTLFTextFieldHostFormat"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2894 -*- */
lz.ClassAttributeTypes["$lfc$LzTLFTextFieldStyleResolver"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2895 -*- */
lz.ClassAttributeTypes["$lfc$LzTextContainerManager"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2896 -*- */
lz.ClassAttributeTypes["$lfc$LzTextSprite"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3012 -*- */
lz.ClassAttributeTypes["$lfc$LzTimeKernelClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3027 -*- */
lz.ClassAttributeTypes["$lfc$LzTimerService"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3037 -*- */
lz.ClassAttributeTypes["$lfc$LzTrace"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3040 -*- */
lz.ClassAttributeTypes["$lfc$LzURL"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3062 -*- */
lz.ClassAttributeTypes["$lfc$LzUtilsClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3068 -*- */
lz.ClassAttributeTypes["$lfc$LzValueExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3069 -*- */
lz.ClassAttributeTypes["$lfc$LzInitExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzValueExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3072 -*- */
lz.ClassAttributeTypes["$lfc$LzOnceExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzInitExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3079 -*- */
lz.ClassAttributeTypes["$lfc$LzConstraintExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzOnceExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3082 -*- */
lz.ClassAttributeTypes["$lfc$LzAlwaysExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzConstraintExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3087 -*- */
lz.ClassAttributeTypes["$lfc$LzStyleConstraintExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzConstraintExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3090 -*- */
lz.ClassAttributeTypes["$lfc$LzStyleExpr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzValueExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3095 -*- */
lz.ClassAttributeTypes["$lfc$LzStyleAttr"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["$lfc$LzStyleExpr"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3100 -*- */
lz.ClassAttributeTypes["$lfc$LzViewLinkage"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3120 -*- */
lz.ClassAttributeTypes["$lfc$LzWarning"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3123 -*- */
lz.ClassAttributeTypes["$lfc$LzXMLLoader"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3161 -*- */
lz.ClassAttributeTypes["$lfc$LzXMLParser"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3164 -*- */
lz.ClassAttributeTypes["$lfc$LzXMLTranslator"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3171 -*- */
lz.ClassAttributeTypes["$lfc$RegExp"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3193 -*- */
lz.ClassAttributeTypes["$lfc$__LzHttpDatasetPoolClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3201 -*- */
lz.ClassAttributeTypes["$lfc$__LzLeak"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3215 -*- */
lz.ClassAttributeTypes["$lfc$__LzLeaks"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3223 -*- */
lz.ClassAttributeTypes["$lfc$__LzStackFrame"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3258 -*- */
lz.ClassAttributeTypes["audio"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {id: "ID", name: "token", src: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#2340 -*- */
lz.ClassAttributeTypes["font"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#652 -*- */
lz.ClassAttributeTypes["handler"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3292 -*- */
lz.ClassAttributeTypes["include"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {href: "string", type: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3264 -*- */
lz.ClassAttributeTypes["resource"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {name: "token", offsetx: "number", offsety: "number", src: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3314 -*- */
lz.ClassAttributeTypes["security"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3276 -*- */
lz.ClassAttributeTypes["splash"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {hideafterinit: "boolean", persistent: "boolean"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3284 -*- */
lz.ClassAttributeTypes["splashview"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {center: "boolean", name: "token", ratio: "string", resource: "string", x: "number", y: "number"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#3296 -*- */
lz.ClassAttributeTypes["stylesheet"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Instance"], {src: "string"});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#22 -*- */
lz.ClassAttributeTypes["MetaClass"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["Object"], {});/* -*- file: /home/raju/flex4.6/WEB-INF/lps/schema/lfc.lzx#1 -*- */
canvas = new LzCanvas(null, {$CSSDescriptor: {}, $attributeDescriptor: {types: lz.ClassAttributeTypes["canvas"]}, __LZproxied: "false", appbuilddate: "2012-08-15T12:53:23Z", bgcolor: 16777215, embedfonts: true, font: "Verdana,Vera,sans-serif", fontsize: 11, fontstyle: "plain", height: "100%", lpsbuild: "branches/flex4.6@19702 (19702)", lpsbuilddate: "2012-07-20T08:14:21Z", lpsrelease: "Latest", lpsversion: "flex4.6.x", runtime: "swf11", width: "100%"});/* -*- file: classes/simplebox.lzx#3 -*- */
lz.ClassAttributeTypes["simplebox"] = LzNode.mergeAttributeTypes(lz.ClassAttributeTypes["view"], {height: "size", width: "size"});/* -*- file: temp/lzx/main.lzx#8 -*- */
canvas.LzInstantiateView({attrs: {$CSSDescriptor: {}, $attributeDescriptor: {types: lz.ClassAttributeTypes["view"]}, height: 150, resource: "freeImg", width: 150}, "class": LzView}, 1);/* -*- file: temp/lzx/main.lzx#10 -*- */
canvas.LzInstantiateView({attrs: {$attributeDescriptor: {types: lz.ClassAttributeTypes["simplebox"]}, bgcolor: 255, opacity: 0.8, x: 100, y: 100}, "class": $lzc$class_simplebox}, 1);lz["simplebox"] = $lzc$class_simplebox;addChild(canvas.sprite);canvas.initDone();}
public function LzApplication ($0:Sprite = null) {
super($0)
}
}
}
